### ISSUE TITLE
ypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by slvrshot** [AAFC-MBB/parallel_itsx#1]
Hello I am getting this error...would you be able to assist? Thanks!

```
SaulGoodMan-Mac-Pro:Bela_ITS2 sgoodman$ parallel_itsx -i Bela_R1.fasta --cpu 6 --multi_thread T -o output
Traceback (most recent call last):
  File "//anaconda/bin/parallel_itsx", line 4, in <module>
    __import__('pkg_resources').run_script('parallel-itsx==0.0.dev1', 'parallel_itsx')
  File "//anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "//anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1491, in run_script
  File "//anaconda/lib/python2.7/site-packages/parallel_itsx-0.0.dev1-py2.7.egg/EGG-INFO/scripts/parallel_itsx", line 151, in <module>
    
  File "build/bdist.macosx-10.7-x86_64/egg/itsx/parallel.py", line 86, in __call__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by mikeschhorn** [comment]
Hi,
same for me - any help would be greatly appreciated:

tf40403@ABUBU01:~/Desktop/NSIS_lnk/fungi/parallel_itsx$ parallel_itsx -i test.fasta -o test.itsx.out.fasta -t F --cpu 4 --heuristics T --table T --preserve T --complement T
Traceback (most recent call last):
  File "/data/tf40403/miniconda2/bin/parallel_itsx", line 4, in <module>
    __import__('pkg_resources').run_script('parallel-itsx==0.0.dev1', 'parallel_itsx')
  File "/data/tf40403/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/data/tf40403/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/data/tf40403/miniconda2/lib/python2.7/site-packages/parallel_itsx-0.0.dev1-py2.7.egg/EGG-INFO/scripts/parallel_itsx", line 151, in <module>
    
  File "build/bdist.linux-x86_64/egg/itsx/parallel.py", line 86, in __call__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
